use serde::{Deserialize, Serialize};

/// Events generated by the UI thread and sent to the JS runtime
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum UiEvent {
    /// Widget action triggered (button click, etc.)
    WidgetAction {
        widget_id: String,
        action: WidgetActionKind,
    },
}

/// Kind of widget action
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum WidgetActionKind {
    Click,
    ValueChanged(f64),
}

/// Keyboard modifier state
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct KeyModifiers {
    pub shift: bool,
    pub ctrl: bool,
    pub alt: bool,
    pub meta: bool,
}
