use serde::{Deserialize, Serialize};

/// Events generated by the UI thread and sent to the JS runtime
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum UiEvent {
    /// Widget action triggered (button click, etc.)
    WidgetAction {
        widget_id: String,
        action: WidgetActionKind,
    },
    /// Runtime error emitted by Rust side and forwarded to JS.
    RuntimeError {
        source: String,
        message: String,
        fatal: bool,
    },
}

/// Kind of widget action
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum WidgetActionKind {
    Click,
    ValueChanged(f64),
    HoverChanged(bool),
}
